import time
import os
import winsound
import time
from threading import Thread
def macarena():
    winsound.PlaySound('a.wav',winsound.SND_FILENAME)
    pass
def MANEVRA():
    i=0
    os.system('cls' if os.name == 'nt' else 'clear')
    while i!=6:
        print("A    ")
        print("       /\     ")
        print("    __(^^)__")
        print("    |\.  ./| ")
        print("    | \__/ |  ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("NA    ")
        print("       /\      ")
        print("    __(^^)__.__")
        print("    |\.  ./ ")
        print("    | \__/   ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("ENA    ")
        print("      /\       ")
        print("__.__(^^)__.__")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("RENA    ")
        print("      /\         ")
        print("__.__(^^)_o_/¯")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("ARENA    ")
        print("      /\     ")
        print("¯\_O_(^^)_O_/¯")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("CARENA    ")
        print("      /\    ")
        print("¯\_o_(^^)_o_/¯")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("ACARENA    ")
        print("/    /\       ")
        print("\_o_(^^)_o_/¯")
        print("   \.  ./  ")
        print("    \__/   ")
        print("    /$$\    ")
        print("  _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("MACARENA")
        print("/    /\    \.")
        print("\_o_(^^)_o_/")
        print("   \.  ./  ")
        print("    \__/   ")
        print("    /$$\    ")
        print("  _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print(" MACARENA")
        print("      /\    \.")
        print("¯\_o_(^^)_o_/")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("  MACARENA")
        print("      /\       ")
        print("¯\_o_(^^)_o_/¯")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("   MACARENA")
        print("      /\       ")
        print("__.__(^^)_o_/¯")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\   ")
        print("   _/¯¯¯¯\_ ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        i+=1
        print("     MACARENA")
        print("      /\         ")
        print("__.__(^^)__.__")
        print("    \.  ./  ")
        print("     \__/   ")
        print("     /$$\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("       MACARENA")
        print("       /\      ")
        print(" __.__(^^)__")
        print("     \.  ./| ")
        print("      \__/ |  ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("       MACARENA")
        print("       /\    ")
        print("    __(^^)__")
        print("    |\.  ./| ")
        print("    | \__/ |  ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("       MACARENA")
        print("       /\   ")
        print("    __(^^)_")
        print("    |\.  \| ")
        print("    | \__/   ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("       MACARENA")
        print("       /\    ")
        print("     _(^^)_")
        print("     |/  \| ")
        print("      \__/   ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("       MACARENA")
        print("       /\    ")
        print("     _(^^)__")
        print("     |/  ./| ")
        print("      \__/ |  ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("       MACARENA")
        print("       /\    ")
        print("    __(^^)__")
        print("    |\.  ./| ")
        print("    | \__/ |  ")
        print("      /$$\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("A       MACAREN")
        print("       |\ ")
        print("       (ε)   ")
        print("      /|.\  ")
        print("      || |  ")
        print("      /¯¯\      ")
        print("      ¯||_¯       ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("NA        MACARE")
        print("       /\     ")
        print("    __(##)__")
        print("    |\    /| ")
        print("    | \__/ |  ")
        print("      /00\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("ENA        MACAR")
        print("       /\   ")
        print("    __(##)__.__")
        print("    |\    / ")
        print("    | \__/   ")
        print("      /00\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("RENA        MACA")
        print("       /\       ")
        print(" __.__(##)__.__")
        print("     \    / ")
        print("      \__/   ")
        print("      /00\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("ARENA        MAC")
        print("      /\       ")
        print("__.__(##)_o_/¯")
        print("    \    /  ")
        print("     \__/   ")
        print("     /00\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("CARENA        MA")
        print("      /\      ")
        print("¯\_O_(##)_O_/¯")
        print("    \    /  ")
        print("     \__/   ")
        print("     /00\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("ACARENA        M")
        print("      /\       ")
        print("¯\_o_(##)_o_/¯")
        print("    \    /  ")
        print("     \__/   ")
        print("     /00\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("MACARENA        ")
        print("/    /\       ")
        print("\_o_(##)_o_/¯")
        print("   \    /  ")
        print("    \__/   ")
        print("    /00\    ")
        print("  _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print(" MACARENA        ")
        print("/    /\    \.")
        print("\_o_(##)_o_/")
        print("   \    /  ")
        print("    \__/   ")
        print("    /00\    ")
        print("  _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("  MACARENA        ")
        print("      /\    \.")
        print("¯\_o_(##)_o_/")
        print("    \    /  ")
        print("     \__/   ")
        print("     /00\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("   MACARENA        ")
        print("      /\        ")
        print("¯\_o_(##)_o_/¯")
        print("    \    /  ")
        print("     \__/   ")
        print("     /00\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("    MACARENA        ")
        print("      /\        ")
        print("__.__(##)_o_/¯")
        print("    \    /  ")
        print("     \__/   ")
        print("     /00\   ")
        print("   _/¯¯¯¯\_ ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        i+=1
        print("     MACARENA        ")
        print("      /\        ")
        print("__.__(##)__.__")
        print("    \    /  ")
        print("     \__/   ")
        print("     /00\    ")
        print("   _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("      MACARENA        ")
        print("       /\     ")
        print(" __.__(##)__")
        print("     \    /| ")
        print("      \__/ |  ")
        print("      /00\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("      MACARENA        ")
        print("       /\    ")
        print("    __(##)__")
        print("    |\    /| ")
        print("    | \__/ |  ")
        print("      /00\    ")
        print("    _/¯¯¯¯\_   ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("      MACARENA        ")
        print("       |\     ")
        print("       (ε)   ")
        print("      /|.\  ")
        print("      || |  ")
        print("      /¯¯\      ")
        print("      ¯||_¯       ")
        time.sleep(0.5)
        os.system('cls' if os.name == 'nt' else 'clear')

while True:
    thread=Thread(target=macarena)
    thread.start()
    MANEVRA()